-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 18d7035de5388cc7775be57f529c154bf541aab9
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
    -   id: debug-statements
    -   id: flake8
        'language_version:': 2
